# @todo build on CI server first, then copy files to avoid downtime

name: Deploy Game

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build containers
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/game-beta
            git reset --hard
            git checkout beta
            git pull
            npm install
            npm run build
            pm2 reload game-beta
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
